### ISSUE TITLE
How can i display capture image?

### ISSUE THREAD

**Issue by sskraj** [kasperkamperman/MobileCameraTemplate#1]
any ways to capture image display and save the image in disk..

**Comment by kasperkamperman** [comment]
You have to implement that yourself. You can display it with canvas, see this line. 
```
// if you'd like to show the canvas add it to the DOM
var canvas = document.createElement('canvas');
```

Function to save is toDataURL. 
Here a starting point:
https://stackoverflow.com/questions/10673122/how-to-save-canvas-as-an-image-with-canvas-todataurl
