### ISSUE TITLE
ViewFinder

### ISSUE THREAD

**Issue by patv2learn** [kasperkamperman/MobileCameraTemplate#11]
Hey @kasperkamperman, first of all thanks for the great project and clean code with document. 

I have a question, is there any way I can add ViewFinder kind of functionality while working on phone camera from html? If yes, any idea how to do that? I have to provide document scanning (just picture taking not reading/OCR) and for that I want to add some kind of frame while camera preview stream is ON. This is something like the box you can see in following image.
![card_scan](https://user-images.githubusercontent.com/27989386/84586301-39edad00-adcd-11ea-97e6-ead54418936b.gif)

Any help in this would be a great help. I am trying to work on this but no idea where to start. I know this is possible for sure because there are many browser based barcode scanner do offer such feature but I want to add a rectangle on screen and want user to fit document in that box.

Thanks.

**Comment by kasperkamperman** [comment]
With html, css you can overlay everything (check z-index on w3schools). I
can help you, but thats paid work.

Kasper

**Comment by patv2learn** [comment]
Sure, lets talk about it. Do you want to discuss in private chat? Please send me your Skype ID or any other way you are comfortable to discuss it. Thanks.
