### ISSUE TITLE
switch camera on PC

### ISSUE THREAD

**Issue by tolaysha** [kasperkamperman/MobileCameraTemplate#12]
Switch camera is't work on pc(i have 2 cam on my laptop, native and usb cam ), becouse PC is't support facingMode user and environment. I think you should use deviceId, when you detect pc or laptop on client browser

**Comment by kasperkamperman** [comment]
Normally I don't show it on PC/Mac. 
You see the switch camera button anyway? 
What does it do?

**Comment by tolaysha** [comment]
Yes i see it. My first camera just blinks when i push the button
