### ISSUE TITLE
Some images having problems

### ISSUE THREAD

**Issue by boxidilshan** [kasperkamperman/MobileCameraTemplate#13]
Tried to run your code in different devices and I am facing issues with the front camera of some Android devices. Android version is 9. Please see the attached image. Some images are generated as layers like this. Is there anyway I can fix this issue or am I doing something wrong.

![test](https://user-images.githubusercontent.com/1705430/92621538-8e77ca00-f2e1-11ea-8445-198e20917575.png)

Thank you for your great work. Keep it up.

**Comment by kasperkamperman** [comment]
I have no idea, I never came across this problem. It might be a compression issue. You could try to store in a different format (jpeg, png) to see if this problem persists. 

Keep me up to date if you find the problem.

**Comment by boxidilshan** [comment]
Yes this is intermittent and found in only lesser number of people. Trying to figure that out. Will keep you posted.

**Comment by boxidilshan** [comment]
When I change this to jpg issue seems to be fixed. Changed to 'image/jpeg' and 0.9. However now I see some images are stretched in certain cases. Hence the faces are captured differently. Have used following. Is there anyway we can maintain the same aspect ratio and just crop the image?

```
    video: {
      width: { ideal: size },
      height: { ideal: size },
      //width: { min: 1024, ideal: window.innerWidth, max: 1920 },
      //height: { min: 776, ideal: window.innerHeight, max: 1080 },
      facingMode: currentFacingMode,
    },
```

**Comment by boxidilshan** [comment]
If you keep like above we can get rid of the above issue.

```
        width: { ideal: window.innerWidth },
        height: { ideal: window.innerHeight },
```

**Comment by kasperkamperman** [comment]
I'm not clear what solved the issue?

Did jpeg 0.9 solve it?

And you changed the code below from ideal: size, to specific window innerWidth, innerHeight?
```
width: { ideal: size },
height: { ideal: size },
```

to: 
```
width: { ideal: window.innerWidth },
height: { ideal: window.innerHeight },
```

**Comment by boxidilshan** [comment]
Yes making it to jpeg 0.9 solved the issue. Earlier it was png. Something is going on with png with some of the Android devices. It consistently reproduced this for some users with Android devices.  The other one is a separate issue where the image is stretched and distorted in some devices. When I use innerWidth and innerHeight it seems to be fine as it doesn't do any processing with the image.

**Comment by kasperkamperman** [comment]
Thanks. 

Strange that "ideal" will stretch/distort, because it should set ideal not change the aspect ratio. 
Did you find which devices? 

Where those the same devices that also had PNG problems? 

Could you narrow it down to certain brand, model, Android version?

**Comment by boxidilshan** [comment]
Yes got feedback from 1 tester. It gave above results all the time for Samsung galaxy J7. Yes its the same device that had png issue.

**Comment by kasperkamperman** [comment]
Did you inform which Android OS he is using and which browser (Samsung,
Chrome or something else?).

**Comment by boxidilshan** [comment]
Its Android version 9 with Chrome browser.
