### ISSUE TITLE
could not find camera

### ISSUE THREAD

**Issue by arigus** [kasperkamperman/MobileCameraTemplate#15]
downloaded current  code and it could not fix camera says browser not support camera etc. but works fine with demo link on the same mobile.
Please, advice

**Comment by kasperkamperman** [comment]
Did you host it on a secure url (https), otherwise browsers won't allow camera usage?

Please give more details about browser, OS otherwise I can't give any further support.

**Comment by arigus** [comment]
thanks for promt reply! indeed i tested from without ssl. i working on php (codeigniter). do you provide samples?

**Comment by kasperkamperman** [comment]
👍 I have no ready made code samples now.
