### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by nicejava** [kasperkamperman/MobileCameraTemplate#4]
I try test your demo https://demo.kasperkamperman.com/mobilecamtemplate open with safari on iphone it's can open camera of mobile . But when i try run code in github then try open safari it's can't open camera of mobile. What happen ? .. thank you

**Comment by nicejava** [comment]
Have responce on safari iphone - > Please install an external webcam device

**Comment by kasperkamperman** [comment]
You need to run it on a secure server (https).

**Comment by nicejava** [comment]
Try https response like this 

![image](https://user-images.githubusercontent.com/6760497/71522472-6bde8600-28f7-11ea-9109-b21a366b9eee.png)

**Comment by kasperkamperman** [comment]
Thanks I think it's answered, so I close this issue.
