### ISSUE TITLE
demo flip camera button not show on iphone

### ISSUE THREAD

**Issue by nijisakai** [kasperkamperman/MobileCameraTemplate#5]
**OS**
`iOS 13.3`
`iPhone 8 Plus`
`Safari`

![微信图片_20200113145030](https://md.hass.live/%E5%BE%AE%E4%BF%A1%E5%9B%BE%E7%89%87_20200113145030.jpg)

Thank you !

**Comment by nijisakai** [comment]
it works all well after i change  `Setting`-->`Safari`-->`Camera` from **Ask** to **Allow** : )

**Comment by kasperkamperman** [comment]
Thanks for reporting this. 

I could reproduce this and I've fixed it in the latest version. 
On Safari first permission has to be given in order to detect the amount of cameras (used to show that button or not).
