### ISSUE TITLE
install External webcam device 

### ISSUE THREAD

**Issue by ahasantech** [kasperkamperman/MobileCameraTemplate#6]
Hello, thanks for your source code, the source code used my local server, and access my mobile, when used the browser then show Please install External webcam device, but my mobile already have cam. 

![img](https://user-images.githubusercontent.com/61349388/75315983-97d9a180-587d-11ea-8a3a-5943e1b95f83.jpeg)

**Comment by kasperkamperman** [comment]
If you run on localhost non secure this can happen. Do you test with safari
or chrome. Please provide more details.

**Comment by ahasantech** [comment]
Thanks for support, solved the issue
